---

- name: check postgresql directories
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
  with_items:
    - "/etc/postgresql/{{ postgresql_version }}"
    - "/etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}"

- name: configure postgresql.conf
  sudo: yes
  template:
    dest: "/etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/postgresql.conf"
    src: postgresql.conf.j2
    mode: 0644
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
  notify: restart postgresql

- name: configure pg_hba.conf
  sudo: yes
  template:
    dest: "{{ postgresql_cfg_hba_file }}"
    src: pg_hba.conf.j2
    mode: 0644
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
  notify: reload postgresql
  tags: postgresl_users

- name: configure pg_ident.conf
  sudo: yes
  template:
    dest: "/etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/pg_ident.conf"
    src: pg_ident.conf.j2
    mode: 0644
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
  notify: reload postgresql
