---

- include: validation.yml
  tags: always

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags: postgresl_packages

- include: setup_cluster.yml
  tags: postgresl_cluster

- include: setup_ssl.yml
  when: postgresql_cfg_ssl is defined and postgresql_cfg_ssl == 'on'

- include: replication.yml
  when: postgresql_replication

- include: configuration.yml
  tags: postgresl_configuration

- include: setup_databases.yml
  when: postgresql_replication_role == 'master' or not postgresql_replication
  tags: postgresl_databases

- include: setup_users.yml
  when: postgresql_replication_role == 'master' or not postgresql_replication
  tags: postgresl_users

#- include: setup_privileges.yml
