---

- include: validation.yml
  tags: postgresl_validation

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags: postgresl_packages

- include: setup_cluster.yml
  tags: postgresl_cluster

- include: setup_ssl.yml
  when: postgresl_configuration.ssl is defined and postgresql_config == 'on'

- include: replication.yml
  when: postgresql_replication

- include: configuration.yml
  tags: postgresl_configuration

- include: setup_users.yml
#  when: (not postgresql_replication) or postgresql_replication_role == 'master'
  tags: postgresl_users

- include: setup_databases.yml
  when: (not postgresql_replication) or postgresql_replication_role == 'master'
  tags: postgresl_databases

#- include: setup_privileges.yml

