---

- name: stop postgresql server
  sudo: yes
  service:
    name: postgresql
    state: stopped
  when: postgresql_replication_role == 'slave'

- name: remove data_directory
  sudo: yes
  file:
    path: "{{ postgresql_cfg_data_directory }}"
    state: absent
  when: postgresql_replication_role == 'slave'

- name: replication | postgresql initial replication
  sudo: yes
  sudo_user: "{{ postgresql_superuser }}"
  shell: >
    PGPASSWORD={{ postgresql_users_replication.0.password }} pg_basebackup
    -X stream -h {{ postgresql_replication_master_ip }}
    -D {{ postgresql_cfg_data_directory }}
    -U {{ postgresql_users_replication.0.user }} -v -P
  when: postgresql_replication_role == 'slave'
  notify: restart postgresql

- name: replication | create recovery.conf file
  sudo: yes
  template:
    src: recovery.conf.j2
    dest: "{{ postgresql_cfg_data_directory }}/recovery.conf"
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
  when: postgresql_replication_role == 'slave'

