---

- name: stop postgresql server
  sudo: yes
  service:
    name: postgresql
    state: stopped
  when: postgresql_replication_role == 'slave'

- name: remove data_directory
  sudo: yes
  file:
    path: "{{ postgresql_config.data_directory }}"
    state: absent
  when: postgresql_replication_role == 'slave'

- name: replication | postgresql initial replication
  sudo: yes
  sudo_user: postgres
  shell: >
    PGPASSWORD={{ postgresql_users_replication.0.password }} pg_basebackup
    -X stream -h {{ master_ip }}
    -D {{ postgresql_config.data_directory }}
    -U {{ postgresql_users_replication.0.user }} -v -P
  when: postgresql_replication_role == 'slave'
  notify: restart postgresql

- name: replication | create recovery.conf file
  sudo: yes
  template:
    src: recovery.conf.j2
    dest: "{{ postgresql_config.data_directory }}/recovery.conf"
    owner: postgres
    group: postgres
  when: postgresql_replication_role == 'slave'

