---

#- name: create .ssh directory
#  sudo: yes
#  sudo_user: "{{ postgresql_superuser }}"
#  file:
#    path: "~/.ssh"
#    owner: "{{ postgresql_superuser }}"
#    group: "{{ postgresql_superuser }}"
#    state: directory
#
#- name: copy ssh key
#  sudo: yes
#  sudo_user: "{{ postgresql_superuser }}"
#  copy:
#    dest: "~/.ssh/id_rsa"
#    content: "{{ postgresql_repmgr_private_key }}"
#    mode: 0600
#    owner: "{{ postgresql_superuser }}"
#    group: "{{ postgresql_superuser }}"
#
#- name: copy authorized_keys
#  sudo: yes
#  sudo_user: "{{ postgresql_superuser }}"
#  copy:
#    dest: "~/.ssh/authorized_keys"
#    content: "{{ postgresql_repmgr_public_key }}"
#    mode: 0600
#    owner: "{{ postgresql_superuser }}"
#    group: "{{ postgresql_superuser }}"

- name: create repmgr user
  sudo: yes
  sudo_user: "{{ postgresql_superuser }}"
  postgresql_user:
    name: "{{ postgresql_repmgr_user }}"
    password: "{{postgresql_repmgr_password }}"
    role_attr_flags: LOGIN,SUPERUSER,REPLICATION
    state: "present"
    fail_on_user: no
  when: postgresql_repmgr_type == 'master'

- name: create repmgr database
  sudo_user: "{{ postgresql_superuser }}"
  postgresql_db:
    name: "{{ postgresql_repmgr_database }}"
    owner:  "{{ postgresql_repmgr_user }}"
  when: postgresql_repmgr_type == 'master'

- name: repmgr | create config directory
  sudo: yes
  file:
    path: "{{ postgresql_repmgr_conf | dirname }}"
    state: directory

- name: repmgr | create repmgr.conf
  sudo: yes
  template:
    src: repmgr.conf.j2
    dest: "{{ postgresql_repmgr_conf }}"
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"

- name: repmgr | check cluster status
  sudo_user: "{{ postgresql_superuser }}"
  command: "repmgr -f {{ postgresql_repmgr_conf  }} cluster show"
  ignore_errors: true
  register: repmgr_status

- name: stop postgresql server
  sudo: yes
  service:
    name: postgresql
    state: stopped
  when: postgresql_repmgr_type == 'standby' and repmgr_status|failed

- name: remove data_directory
  sudo: yes
  file:
    path: "{{ postgresql_cfg_data_directory }}"
    state: absent
  when: postgresql_repmgr_type == 'standby' and repmgr_status|failed

- name: create data_directory
  sudo: yes
  file:
    path: "{{ postgresql_cfg_data_directory }}"
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"
    state: directory
  when: postgresql_repmgr_type == 'standby' and repmgr_status|failed

- name: pgpass
  sudo_user: "{{ postgresql_superuser }}"
  template:
    src: pgpass.j2
    dest: ~/.pgpass
    mode: 0600

- name: sync from master
  sudo_user: "{{ postgresql_superuser }}"
  command: "repmgr -f {{ postgresql_repmgr_conf }}  --verbose --ignore-external-config-files -D {{ postgresql_cfg_data_directory  }} -d {{ postgresql_repmgr_database }} -U {{ postgresql_repmgr_user }} standby clone {{ postgresql_repmgr_master_ip }}"
  when: postgresql_repmgr_type == 'standby' and repmgr_status|failed

- name: start postgresql server
  sudo: yes
  service:
    name: postgresql
    state: started

- name: repmgr | setup cluster
  sudo_user: "{{ postgresql_superuser }}"
  command: "repmgr -f {{ postgresql_repmgr_conf }} --verbose --force {{ postgresql_repmgr_type }} register"
  when: repmgr_status|failed

