---

- name: create repmgr user
  sudo: yes
  sudo_user: "{{ postgresql_superuser }}"
  postgresql_user:
    name: "{{ postgresql_repmgr_user }}"
    password: "{{postgresql_repmgr_password }}"
    role_attr_flags: LOGIN,SUPERUSER,REPLICATION
    state: "present"
    fail_on_user: no

- name: create repmgr database
  sudo_user: "{{ postgresql_superuser }}"
  postgresql_db:
    name: "{{ postgresql_repmgr_database }}"
    owner:  "{{ postgresql_repmgr_user }}"

- name: repmgr | create config directory
  sudo: yes
  file:
    path: "{{ postgresql_repmgr_conf | dirname }}"
    state: directory

- name: repmgr | create repmgr.conf
  sudo: yes
  template:
    src: repmgr.conf.j2
    dest: "{{ postgresql_repmgr_conf }}"
    owner: "{{ postgresql_superuser }}"
    group: "{{ postgresql_superuser }}"

- name: repmgr | check cluster status
  sudo: yes
  command: "repmgr -f {{ postgresql_repmgr_conf  }} cluster show"
  ignore_errors: true
  register: repmgr_status

- name: repmgr | setup cluster
  sudo: yes
  command: "repmgr -f {{ postgresql_repmgr_conf }} --verbose {{ postgresql_repmgr_type }} register"
  when: repmgr_status|failed

