---

- name: create postgresql users
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.roles | join(',') | upper | default(None) }}"
    state: "{{ item.state | default('present') }}"
    fail_on_user: no
  with_items: postgresql_users

