---

- name: create ssl directories if needed
  file:
    path: "{{ item }}"
    owner: postgres
    group: postgres
    state: directory
    mode: 0700
  with_items:
    - postgresql_ssl.cert_filepath | dirname
    - postgresql_ssl.key_filepath  | dirname

- name: Copying ssl keys
  copy:
    content: "{{ postgresql_ssl.key }}"
    dest: "{{ postgresql_ssl.key_filepath"
    owner: postgres
    group: postgres
    mode: 0600

- name: Copying ssl certs
  copy:
    content: "{{ postgresql_ssl.cert }}"
    dest: "{{ postgresql_ssl.cert_filepath }}"
    owner: postgres
    group: postgres
    mode: 0644
