---

- name: create postgresql users
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ item.0.user }}"
    password: "{{ item.0.password | default(None)}}"
    db: "{{ item.1.database if (item.1.database is defined and item.1.database != 'all') else None }}"
    role_attr_flags: "{{ (item.0.roles | default('')) | join(',') | upper }}"
    state: "{{ item.0.state | default('present') }}"
    fail_on_user: no
  with_subelements_safe:
    - postgresql_users
    - databases

- name: create postgresql users priv
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ item.0.user }}"
    db: "{{ item.1.database }}"
    state: "{{ item.0.state | default('present') }}"
    priv: "{{ item.1.priv | default(None) }}"
    fail_on_user: no
  with_subelements_safe:
    - postgresql_users
    - databases
  when: >
    item.1.database is defined and item.1.database != 'all'
    and
    item.1.priv is defined

- name: create replication postgresql users
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    role_attr_flags: LOGIN,REPLICATION
    state: "{{ item.state | default('present') }}"
    fail_on_user: no
  with_items: postgresql_users_replication
  when: postgresql_replication and postgresql_users_replication is defined
